# Generated by Django 5.2 on 2025-04-11 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.CharField(choices=[('regulation', 'Regulation'), ('rule', 'Rule'), ('guideline', 'Guideline')], default='regulation', max_length=50),
        ),
    ]
