# Generated by Django 5.2 on 2025-04-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='type',
            field=models.CharField(choices=[('regulation', 'Regulation'), ('circular', 'Circular'), ('guideline', 'Guideline'), ('law', 'Law'), ('other', 'Other')], default='regulation', help_text='Type of the document', max_length=50),
        ),
    ]
