# Generated by Django 5.2 on 2025-04-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_regulation_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='regulation',
            name='effective_date',
            field=models.DateField(blank=True, help_text='Date when the regulation becomes effective', null=True),
        ),
        migrations.AddField(
            model_name='regulation',
            name='expiry_date',
            field=models.DateField(blank=True, help_text='Date when the regulation expires', null=True),
        ),
        migrations.AddField(
            model_name='regulation',
            name='issue_date',
            field=models.DateField(blank=True, help_text='Date when the regulation was issued', null=True),
        ),
        migrations.AlterField(
            model_name='regulation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_compliance_review', 'Awaiting Compliance Review'), ('reviewed_by_compliance', 'Reviewed by Compliance'), ('action_required_from_department', 'Action Required from Department'), ('department_response_submitted', 'Department Response Submitted'), ('returned_for_department_rework', 'Returned for Department Rework'), ('awaiting_final_compliance_approval', 'Awaiting Final Compliance Approval'), ('fully_approved', 'Fully Approved')], default='draft', max_length=50),
        ),
    ]
